language: cpp
dist: trusty
sudo: required

env:
  global:
    # works around upstream/google depot-tools suck :(
    - DEPLOY_ARCHIVE=${TRAVIS_BUILD_DIR}/../src/dist/dr-breakpad-${TRAVIS_OS_NAME}-${TRAVIS_TAG}.tar.xz

before_install: ./scripts/travis-checkout.sh

install: ./scripts/travis-install-${TRAVIS_OS_NAME}.sh

before_script:
- qbs setup-toolchains --detect
- qbs config defaultProfile ${QBS_PROFILE}

matrix:
  include:
  - os: linux
    env: QBS_PROFILE=gcc PATH=/opt/qt58/bin:$PATH
  - os: osx
    env: QBS_PROFILE=clang

script:
- qbs install --install-root dist -p breakpad_client debug
- qbs install --install-root dist release
- tree ./dist

after_success:
- pushd dist && tar -cvJf ${DEPLOY_ARCHIVE} * ; popd

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: RMEj1hTy2L2pOOvjyp4XUqBiwNzZ28srdsj2X1g/2X1muXdCggsxWzy5khSsW2jQ4OSv3yO7+DsUsGsAI/6E+tjW3GklmMtJWBQWZ2BtukgLlPDwnGX8XCEiEO+1vaWjakYmU3Rx+15SI2LA++7fYt2XVy3Upm1hQeNsC6d44N1Pipx/ADOx09Ak7nWgYfkCymKiODaP7jSWTh+0AjWh0J/mkurEtCh3hN6ZIljS9D4KX8TVfvt6NrwwC5eSq6X4JYSM6x5cNfGYzEhVvCBN8XSCB1w50KiVsUP0NfOALd9RmMBXGIeqKIuTAP61CuTTkj0NvgnTNsfrDNJQouwIrDHXFr6hBDKO+oSmGAZXMuVi61sx0I0nlid7LiOlfBD1AVodsCauemMN3q60H9/xE2ZYAeflqVgRl0EDKcSDZZ4cDIDl6ODnr23xa4Ct3Qv7yiXpbS0dEBYYiKhZbCbmBIsTLZzd+XlZ/iZwvD7TiTY/nFJnBjM7Pa3d0O3mTec/HcXq0lpvCMSqR7afFgsfpsmYPNsIVOBV5C2nI1d8OLiRe6bw2hg5qcV9M3Hq77XFCXjiRwXxh2EgkbXmnrJkjqNH/5FBemBorXgyFj72dLL8Ms8UJjehr1y3QILY1iGxMY706tZEjgxhGr+AIWUy8a4t9Oyf2J/wMGMohFzs788=
  file: ${DEPLOY_ARCHIVE}
  on:
    repo: d-ronin/breakpad
    tags: true
