image: Visual Studio 2015
shallow_clone: true
clone_depth: 1

install:
  - cinst qbs
  - qbs setup-toolchains --detect
  - qbs config defaultProfile MSVC2015-x86

before_build:
  - ps: $env:PROJECT_REV = If ($env:APPVEYOR_REPO_TAG_NAME) {$env:APPVEYOR_REPO_TAG_NAME} Else {$env:APPVEYOR_REPO_COMMIT}

build_script:
  - qbs install --install-root dist -p breakpad_client debug
  - qbs install --install-root dist release

after_build:
  - ps: tree /F dist

artifacts:
  - path: dist
    name: dr-breakpad-msvc2015-$(PROJECT_REV)
    type: zip

deploy:
  provider: GitHub
  description: 'Automatic build'
  auth_token:
    secure: H2rTOfsuiqkTmu7tpwMClKRUHwQ61WoNIaC/7x95YLjTsxBMD70VHRaQnV9g7uGX
  artifact: dr-breakpad-msvc2015-$(PROJECT_REV).zip
  draft: true
  prerelease: false
  force_update: true
  on:
    appveyor_repo_tag: true
